# This is a basic workflow to help you get started with Actions

name: Collocation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      concordance-file:
        type: choice
        description: concordance file
        options: 
        - all
        - concordance-download_1985.txt
        - concordance-download_2020.txt
      runs-on:
        type: choice
        description: Operating system
        options: 
        - ubuntu-latest
        - macos-latest
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ github.event.inputs.runs-on }}
    name: Setup Python NLP work environment

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: "3.8.10"
    - name: Install dependencies
      run: |
        python -m venv dev_env
        source dev_env/bin/activate
        python -m pip install --upgrade pip
        python -m pip install -r requirements_${{ github.event.inputs.runs-on }}.txt
        python -m pip freeze > constraints.txt
        cat constraints.txt
    - name: Execute NLP processing on ${{ github.event.inputs.concordance-file }}
      working-directory: ./Collocation
      run: |
        ls
        source ../dev_env/bin/activate
        python collocation.py -i ${{ github.event.inputs.concordance-file }}
        ls
    - name: Archive NLP inputs
      uses: actions/upload-artifact@v4
      with:
        name: NLP-inputs
        path: "./Collocation/concordance-download_*.txt"

    - name: Archive NLP results
      uses: actions/upload-artifact@v4
      with:
        name: NLP-outputs
        path: "./Collocation/collocation_novels_*.csv"
