# This is a basic workflow to help you get started with Actions

name: CR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: ["maria/dev","main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Setup Python NLP work environment

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m venv dev_env
        source dev_env/bin/activate
        python -m pip install --upgrade pip
        python -m pip install -r requirements_ubuntu.txt
        python -m pip freeze > constraints.txt
        cat constraints.txt
    - name: Execute NLP processing on Docs/2024_07_07
      working-directory: ./Docs/2024_07_07
      run: |
        ls
        source ../../dev_env/bin/activate
        python thing2.py
        ls
    - name: Archive NLP results
      uses: actions/upload-artifact@v4
      with:
        name: NLP-report
        path: ./Docs/2024_07_07/collocation_novels_2000.csv
