# This workflow will install Python dependencies, run code with a single version of Python

name: Python application

on:
  workflow_dispatch:
    inputs:
        input: 
            description: "Test_Input"
            required: false
            default: "Default"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements_ubuntu.txt ]; then pip install -r requirements_ubuntu.txt; fi
    - name: Work in progress
      run: |
        ls
